---
- name: Generate Hosts File
  hosts: balancer
  remote_user: kube
  become: true
  gather_facts: true
  vars:
    my_file: /etc/haproxy/haproxy.cfg
    my_template: templates/haproxy.j2
  tasks:
    - name: Update YUM package
      dnf: name=* state=latest
    - name: Install haproxy
      dnf:
        name: haproxy
        state: present
    - name: Stop haproxy service
      service:
        name: haproxy
        state: stopped
    - name: Set setsebool -P haproxy_connect_any=1
      command: setsebool -P haproxy_connect_any=1
    - name: Create "{{ my_file }}"
      template:
        src: "{{ my_template }}"
        dest: "{{ my_file }}"
        owner: root
        group: root
        mode: "0644"
    - name: start haproxy service
      service:
        name: haproxy
        state: started

